import streamlit as st
import sqlite3
import pandas as pd
import plotly.express as px

# ==========================================
# STREAMLIT DASHBOARD: AUTONOMOUS DDI AUDITOR
# ==========================================
# This script creates an interactive web dashboard to visualize the
# safety audit results generated by our AI agents.
# ==========================================

st.set_page_config(page_title="DDI Auditor Dashboard", page_icon="🏥", layout="wide")

st.title("🏥 Autonomous DDI Auditor - Safety Dashboard")
st.markdown("---")

# Function to load data from SQLite
@st.cache_data
def load_data():
    try:
        import os
        BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        DB_PATH = os.path.join(BASE_DIR, "outputs", "audit_results.db")
        
        conn = sqlite3.connect(DB_PATH)
        # We need to loop through all tables and combine them for the dashboard
        cursor = conn.cursor()
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        tables = [row[0] for row in cursor.fetchall() if row[0] != "sqlite_sequence"]
        
        df_list = []
        for table in tables:
            query = f"SELECT *, '{table}' as Department FROM {table}"
            df_temp = pd.read_sql_query(query, conn)
            df_list.append(df_temp)
            
        df = pd.concat(df_list, ignore_index=True)
        conn.close()
        return df
    except Exception as e:
        st.error(f"Error loading database: {e}")
        return pd.DataFrame()

# Load the data
df = load_data()

if df.empty:
    st.warning("No audit data found. Please run `main.py` first to generate the database.")
else:
    # Top Level Metrics
    st.subheader("📊 Executive Summary")
    
    # Calculate Metrics
    total_patients_audited = df['patient_name'].nunique()
    total_interactions_checked = len(df)
    
    # Identify HIGH RISK (Literature FLAG or Chemical FLAG)
    df['Is_High_Risk'] = df['literature_risk'].str.contains('KNOWN RISK', na=False) | df['biochem_risk'].str.contains('HIGH STRUCTURAL SIMILARITY', na=False)
    high_risk_interactions = df['Is_High_Risk'].sum()
    unique_high_risk_patients = df[df['Is_High_Risk']]['patient_name'].nunique()

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Patients Audited", total_patients_audited)
    col2.metric("Drug Pairs Checked", total_interactions_checked)
    col3.metric("High-Risk Interactions", high_risk_interactions, delta_color="inverse")
    col4.metric("Patients at Risk", unique_high_risk_patients, delta_color="inverse")

    st.markdown("---")

    # Visualizations
    col_chart1, col_chart2 = st.columns(2)
    
    with col_chart1:
        st.subheader("📈 High-Risk Interactions by Department")
        # Filter only high risk
        df_risk = df[df['Is_High_Risk']]
        if not df_risk.empty:
            risk_by_dept = df_risk.groupby("Department").size().reset_index(name="Count")
            fig1 = px.bar(risk_by_dept, x="Department", y="Count", color="Department", 
                          title="Count of Critical Drug-Drug Interactions")
            st.plotly_chart(fig1, use_container_width=True)
        else:
            st.info("No high-risk interactions found to graph.")

    with col_chart2:
        st.subheader("💊 Most Common Interacting Drugs")
        if not df_risk.empty:
            # Combine drug 1 and drug 2 from the risk dataframe to see which is most common
            drugs = pd.concat([df_risk['drug_1'], df_risk['drug_2']])
            top_drugs = drugs.value_counts().head(10).reset_index()
            top_drugs.columns = ['Drug Name', 'Involvement Count']
            
            fig2 = px.pie(top_drugs, values='Involvement Count', names='Drug Name', 
                          title="Top 10 Drugs Causing Alerts")
            st.plotly_chart(fig2, use_container_width=True)

    st.markdown("---")
    
    # Detailed Data Table
    st.subheader("📋 Detailed Safety Audit Log")
    
    # Interactive filtering
    dept_filter = st.selectbox("Filter by Department:", ["All"] + list(df['Department'].unique()))
    
    if dept_filter != "All":
        filtered_df = df[df['Department'] == dept_filter]
    else:
        filtered_df = df
        
    st.dataframe(filtered_df[['patient_name', 'age', 'Department', 'diagnosis', 'drug_1', 'drug_2', 'literature_risk', 'biochem_risk']], 
                 use_container_width=True, hide_index=True)
    
    st.caption("Data generated autonomously by DDI Agent Team (NCBI Literature + RDKit Chemical Analysis).")
